DROP TABLE IF EXISTS inventory;

CREATE TABLE inventory (

  id SERIAL PRIMARY KEY,
  name VARCHAR(250),
  description TEXT

);

INSERT INTO inventory (name , description) VALUES ('Item 1' , 'Item 1 description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO inventory (name , description) VALUES ('Item 2' , 'Item 2 description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO inventory (name , description) VALUES ('Item 3' , 'Item 3 description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO inventory (name , description) VALUES ('Item 4' , 'Item 4 description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO inventory (name , description) VALUES ('Item 5' , 'Item 5 description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO inventory (name , description) VALUES ('Item 6' , 'Item 6 description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO inventory (name , description) VALUES ('Item 7' , 'Item 7 description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');



-- INSERT INTO inventory (name , description) VALUES ('adidas 2018 FIFA World Cup Russia™ Competition Ball' , 'The world''s top teams renew rivalries this summer in Russia. Featuring a thermally bonded seamless construction for a perfect flight, this football is the official match ball of the 2018 FIFA World Cup™. Inspired by Russia''s urban landscapes, a pixelated graphic pays tribute to the iconic Telstar ball.');
-- INSERT INTO inventory (name , description) VALUES ('Argentina adidas Z.N.E. Jacket' , 'The crowd roar as players enter the stadium, but Argentina remain in the zone. Styled after the one players wear as they exit the tunnel, this men''s football jacket features a bold "Argentina" graphic across the back and a woven team crest on the front as reminder of where focus can take you.');
-- INSERT INTO inventory (name , description) VALUES ('2018 FIFA World Cup Russia™ Hoody Red' , 'In 2018, the FIFA World Cup™, the largest football tournament in the world, will be in Russia. 32 teams will fight for the most coveted trophy in football from 14 June to 15 July. The official logo of the 2018 FIFA World Cup Russia™ is printed on the right chest. A warm hood with drawcord and two practical pockets complete this Hoody.');
-- INSERT INTO inventory (name , description) VALUES ('Germany Home Jersey 2018' , 'When West Germany defeated Argentina to complete a hat trick of world titles, they did it in a kit that has since enjoyed the same legendary status as the country''s 1990 heroes.
-- Taking inspiration from that design classic, this men''s football jersey is a replica of the home shirt Germany''s current stars wear. It''s made of sweat-sweeping Climalite, with a slightly looser cut and a woven national badge on the chest. adidas is dedicated to creating products in ways that minimise their environmental impact. This jersey is made with recycled polyester to save resources and decrease emissions.');
